### ISSUE TITLE
Implement UI for facet administration

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [brainvest/dscribe#22]

**Comment by arashbahreini** [comment]
I can handle this issue.

**Comment by AlirezaHaghshenas** [comment]
@arashbahreini  I've already implemented the server-side. Can you please do the client-side?

**Comment by arashbahreini** [comment]
The Client side of property facets is done. please pull my branch and confirm it's structure for properties. 
After your confirmation, I'll design the same structure for entities.
