### ISSUE TITLE
Handle property type error

### ISSUE THREAD

**Issue by arashbahreini** [brainvest/dscribe#26]
If a property is actually int64 but it defines as Integer , we get exception in server and client does not get to know what is the reason of error.
It happens in nullable and not nullable fields also. 
It's better to notify use while he is creating properties instead of at run time.

**Comment by AlirezaHaghshenas** [comment]
We have a few things to consider.

1. For the normal user, they don't need to know about the actual error. They should just be told a generic error. Also, revealing the actual error is considered a security problem.
1. For the user with right privileges, we can show more descriptive error messages.
1. In #27 I suggested a metadata validation tool in administration that checks if the effective metadata and database are compatible.

**Comment by arashbahreini** [comment]
I'm closing the issue due to inactivity.
