### ISSUE TITLE
Error handling in both of the Client and server

### ISSUE THREAD

**Issue by arashbahreini** [brainvest/dscribe#28]
I think we should handle requirement validation in both sides of the project.
1. the client of project there are form validations such as required fields and etc. 
These validations are stands just as warnings. User should stop if required field has not filled yet. 
2. There are unexpected exceptions which appear in backend. E.g if user open 'New Property' dialog and just press save ( without adding any value ) he get an exception i.e 
`'An error occurred while updating the entries. See the inner exception for details.' error. 
`I think we should have [required] and other attributes top of our properties as well as an attribute top of our controller to check `modelState.isValid` in server. Then for each one we need to have an appropriate error message to return to the client.

**Comment by arashbahreini** [comment]
To Addition of this issue I should notice that without handle this issue , application can be in danger of being Table Lock against DDOS attacks as well as any request with invalid modelstate can reach to the DbContext part and open Database Connection and so on ...

Have a look at below links. 

[RESTful API Design: What About Errors?](https://apigee.com/about/blog/technology/restful-api-design-what-about-errors)

[Best practice to return errors in ASP.NET Web API](https://stackoverflow.com/a/22163675/3773888)

**Comment by AlirezaHaghshenas** [comment]
Of course we should validate the data both as early as possible and in the server. So we need some validation in the client, and validation in server before hatting the database.

One point is that we have two different paths, one for metadata and other for data. The metadata path is similar to common CRUD code in every project and can mostly be done using framework provided tools.

The data path is a bit more complex and we need to use metadata to do it.
