### ISSUE TITLE
Validate EntityMetaData and PropertyMetadata on Add, Edit and Delete

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [brainvest/dscribe#3]
This should be a simple validation, more complex validation which covers integrity of metadata as a whole, will be tracked in #4.

**Comment by AlirezaHaghshenas** [comment]
As the client-side is covered in #36 and #37, let's change this issue to only cover the server-side.
The server should return `400 (Bad Request)` with a `json` representation of `ModelState` in the body.

**Comment by arashbahreini** [comment]
I'll handle this issue ;)

**Comment by arashbahreini** [comment]
What if User try to remove an entity which is referenced to one or more properties? 
**Which of the below actions should be performed?** 

1. server should thrown exception i.e you are not able to perform this action ...
2. server should delete entity along with its properties.

**Comment by arashbahreini** [comment]
Done with #44

**Comment by AlirezaHaghshenas** [comment]
@arashbahreini  Please also validate this:
in entity metadata, the tablename should both be a validate tablename in common DBMSs and a valid identifier in c# (probably you can limit it to a much more limited constraint)

**Comment by arashbahreini** [comment]
@AlirezaHaghshenas ok I will handle this by regex.

**Comment by arashbahreini** [comment]
Done and pulled to branch #44
