### ISSUE TITLE
Discuss about deleting an entity

### ISSUE THREAD

**Issue by arashbahreini** [brainvest/dscribe#31]
Currently if user delete an entity he get following error.

`The DELETE statement conflicted with the REFERENCE constraint "FK_Properties_Entities_EntityId". The conflict occurred in database "dscribe_metadata", table "dbo.Properties", column 'EntityId'.
The statement has been terminated.`

Which means there are properties referred to the selected entity.
The question is regarding which policy, application can delete an entity ? 
Should user get an appropriate error message or application should have delete all properties as well ?

**Comment by AlirezaHaghshenas** [comment]
A subset of #3
