### ISSUE TITLE
Error in TableName and PrimaryKey Name

### ISSUE THREAD

**Issue by arashbahreini** [brainvest/dscribe#42]
I've got errors in a specific scenario i.e

I have a table called [SalesLT].[Address] which it's singular and plural names are Address. 
After added entity ( plural name: Address, singular name: Address ) and generated code ( successfully), but at the view time, I got the below exception.

`System.Data.SqlClient.SqlException: 'Invalid object name 'SalesLT.Addresses'.'`

at line 83 , method GetByFilterInternal and file EfCoreEntityHandlerInternal.cs . 

I don't know where Addresses has just come from? I didn't insert this name at any place of the application. 

Another problem is my primary key is AddressId instead of Id. Again application was thrown another exception for it which is 

`System.ArgumentException: 'Instance property 'Id' is not defined for type 'Brainvest.DscribeAdventure.Business.Address''`

**Comment by AlirezaHaghshenas** [comment]
In Metadata, `Entity` has a property named `TableName`
What happens if you set that?

**Comment by arashbahreini** [comment]
In my database > Entity > TableName is NULL . this field was not in add/edit modal so I did not fill it.

**Comment by arashbahreini** [comment]
#45 TableName is solved

**Comment by arashbahreini** [comment]
I will try to solve 
'Instance property 'Id' is not defined for type 'Brainvest.DscribeAdventure.Business.Address''

**Comment by arashbahreini** [comment]
TableName is solve by #45

**Comment by AlirezaHaghshenas** [comment]
> 
> 
> I will try to solve
> 'Instance property 'Id' is not defined for type 'Brainvest.DscribeAdventure.Business.Address''

Let's make this a separate issue. #47
