### ISSUE TITLE
Some information that are only of interest in server (and some administrators) are exposed to all users

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [brainvest/dscribe#67]
In `AppManagementController`, there is an action named `GetAppInstancesInfo`. It was implemented to give clients general information they need about app instances. Now it is expanded to return all required information for an administrator to manage appInstances.

The connection string, in particular, should not be exposed to any, but few privileged users.

My suggestion is to implement another action (probably in another controller), suitable for all users that sends only the required information the client needs.

**Comment by arashbahreini** [comment]
@AlirezaHaghshenas  Do you mean another seperate controller ?
